- name: create ec2 and  route53 records
  hosts: local
  connection: local
  vars:
   sg_id: sg-02e4ac8f46d708889
   ami_id: ami-0220d79f3f480ecf5
   enivron: dev
   instances:
   - mongodb
   - catalogue
  tasks:
   - name: create ec2 instance
     amazon.aws.ec2_instance:
       instance_type: " t3.micro"
       security_group: "{{ sg_id }}"
       image_id: "{{ ami_id }}"
       name: "{{ item } }-{{ enivron }}"
       tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ enivron }}"
        Name: "{{ item }}-{{ enivron }}"
     loop: "{{ instances }}"
     register: "ec2_output"

   - name: print the output
     ansible.builtin.debug:
       msg: " {{ ec2_output }}"
